version: '3.4'

services:
  poc.elasticsearch.demoone:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Serilog__WriteTo__1__Args__nodeUris=http://elasticsearch:9200
      - Serilog__WriteTo__1__Args__indexFormat=poc-from-cluster-demo-one
    ports:
      - "8081:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  poc.elasticsearch.demotwo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Serilog__WriteTo__1__Args__nodeUris=http://elasticsearch:9200
      - Serilog__WriteTo__1__Args__indexFormat=poc-from-cluster-demo-two
    ports:
      - "8082:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
